version: '2'

services:

  client:
    build: ./frontend
    ports:
      - 8080:8080
    #environment:
    #  - SERVER_URL=http://localhost:9000

  backend:
    build: ./backend
    ports:
      - 9000:9000
